<a href="https://colab.research.google.com/github/shiv1122004/ML/blob/main/day26/Encoding_ordinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day26-ordinal-encoding/customer.csv')

In [ ]:
df.sample(5)

    age  gender review education purchased
27   69  Female   Poor        PG        No
40   39    Male   Good    School        No
10   98  Female   Good        UG       Yes
22   18  Female   Poor        PG       Yes
18   19    Male   Good    School        No

In [ ]:
df = df.iloc[:,2:]

In [ ]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
X_train

     review education
7      Poor    School
20  Average    School
11     Good        UG
9      Good        UG
27     Poor        PG
16     Poor        UG
35     Poor    School
34  Average    School
18     Good    School
36     Good        UG
33     Good        PG
1      Poor        UG
22     Poor        PG
5   Average    School
40     Good    School
15     Poor        UG
43     Poor        PG
12     Poor    School
29  Average        UG
17     Poor        UG
38     Good    School
0   Average    School
42     Good        PG
13  Average    School
49     Good        UG
2      Good        PG
37  Average        PG
23     Good    School
6      Good    School
24  Average        PG
47     Good        PG
39     Poor        PG
48     Good        UG
46     Poor        PG
19     Poor        PG
4   Average        UG
10     Good        UG
32  Average        UG
45     Poor        PG
30  Average        UG

In [ ]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [ ]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
X_train = oe.transform(X_train)

In [ ]:
X_train

array([[0., 1.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [1., 2.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 1.]])

In [ ]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
X_train

array([[1., 2.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.]])

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1])